### PR TITLE
Fixes build issues caused by commit 656df513c64e176d3896199aaacf1d0eb…

### PR DESCRIPTION
**Pull request by soderstrom-rikard**
…b73910c,

Commit 656df513c64e176d3896199aaacf1d0eb made it impossible to build u-boot. I'm not using buildroot, so don't know if you have fixes for this issue there.

The solution was rather simple, just merge with upstream (u-boot denx) for cmd_wrap in tools/Makefile. Then add an include for generated/autoconf.h in common/env_embedded.c to get compilation without buildroot working.

Note, I don't actually have the alpha chip board (yet) so can only test that the compilation works. Therefor it might be bad to send this as a pull request to chip/stable. I just wanted to share and contribute. Hope you guys don't mind.

Signoff: Rikard Söderström <soderstrom.rikard@gmail.com>

### CODE REVIEW

**Comment by jasonabele** [comment]
Boris,

In case it helps, I have the same issue with building uboot and Rikard's fix works for me.  Log attached.

I do have a CHIP, so I can build/test, so let me know if I can help

Jason

[uboot.log.txt](https://github.com/NextThingCo/CHIP-u-boot/files/3936/uboot.log.txt)

**Comment by bbrezillon** [comment]
Oops, I just noticed a few words were missing in my previous answer :-/.

Anyway, could you try this patch: http://code.bulix.org/1oavj9-89059 ?

**Comment by jasonabele** [comment]
Boris ... your patch from the previous comment also resolved the build issue for me... thanks!

**Comment by soderstrom-rikard** [comment]
Hi Boris,

I totally agree with you (I have no idea what I was thinking), anyway tested your patch and it builds nicely.

I've also included your patch in my commit here, ba2715a864c14862a566c1de69b913c65018eb15
and also removed commit 4390e5988e37e60af342e6f820967a366f2bb189 from my local repo so that nobody starts using it by accident.

Best regards,
Rikard Söderström

**Comment by bbrezillon** [comment]
Just pushed a fix on the stable/chip branch: first reverting 656df51 and then providing the appropriate fix.

**Pull request closed without merging**
